server:
  port:
    9191
spring:
  application:
    name: api-gateway
#  cloud:
#    gateway:
#      routes:
#        - id: user-service
#          uri: lb://user-service
#          predicates:
#            - Path=/user/**
#        - id: favourite-service
#          uri: lb://favourite-service
#          predicates:
#            - Path=/favourite/**
#
#zuul:
#  routes:
#    users:
#      path: /user/**
#      serviceId: user-service
#    favourites:
#      path: /favourite/**
#      serviceId: favourite-service


eureka:
  client:
    register-with-eureka: true
    fetch-registry: true
    service-url:
      defaultZone: http://${EUREKA_SERVER:localhost}:8761/eureka/
    instance:
      hostname: localhost